
package com.mycompany.ejemplomvc;

public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulouno = new javax.swing.JLabel();
        lblNumeroUno = new javax.swing.JLabel();
        txtPrimerNumero = new javax.swing.JTextField();
        txtSegundoNumero = new javax.swing.JTextField();
        lbNumeroTres = new javax.swing.JLabel();
        btnSuma = new javax.swing.JButton();
        lblTituloCuatro = new javax.swing.JLabel();
        lblTituloCinco = new javax.swing.JLabel();
        lblSuma = new javax.swing.JLabel();
        cbxSeleccionOperacion = new javax.swing.JComboBox<>();
        lblTituloOperacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.borderColor"));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblTitulouno.setText("Programa para sumar dos numeros");

        lblNumeroUno.setText("Numero Uno");

        txtPrimerNumero.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                txtPrimerNumeroComponentHidden(evt);
            }
        });
        txtPrimerNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimerNumeroActionPerformed(evt);
            }
        });

        lbNumeroTres.setText("Numero Dos");

        btnSuma.setText("Sumar");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });

        lblTituloCuatro.setText("La suma de esos numeros es :");

        lblSuma.setText("________________");

        cbxSeleccionOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suma", "Resta", "Multiplicacion", "Division" }));
        cbxSeleccionOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSeleccionOperacionActionPerformed(evt);
            }
        });

        lblTituloOperacion.setText("Elija la operacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTituloCuatro)
                .addGap(18, 18, 18)
                .addComponent(lblSuma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(lblTituloCinco)
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnSuma))
                    .addComponent(lblTitulouno)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbNumeroTres)
                                    .addComponent(lblNumeroUno))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblTituloOperacion)
                                .addGap(32, 32, 32)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPrimerNumero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(cbxSeleccionOperacion, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                            .addComponent(txtSegundoNumero))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulouno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxSeleccionOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloOperacion))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroUno)
                    .addComponent(txtPrimerNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSegundoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNumeroTres))
                .addGap(18, 18, 18)
                .addComponent(btnSuma)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloCuatro)
                    .addComponent(lblTituloCinco)
                    .addComponent(lblSuma))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrimerNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimerNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerNumeroActionPerformed

    private void txtPrimerNumeroComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtPrimerNumeroComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerNumeroComponentHidden

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        // TODO add your handling code here:
        int resultado = 0;
        String opcion= (String) cbxSeleccionOperacion.getSelectedItem();
        int numeroUno= Integer.parseInt(txtPrimerNumero.getText());
        int numeroDos= Integer.parseInt(txtSegundoNumero.getText());
        
        
        lblSuma.setText(String.valueOf(resultado));
        switch (opcion) {
            case "Suma":
                 resultado=numeroUno + numeroDos;
                 lblSuma.setText(String.valueOf(resultado));
                break;
            case "Resta":
                resultado=numeroUno -numeroDos;
                lblSuma.setText(String.valueOf(resultado));
                break;
            case "Multiplicacion":
                resultado=numeroUno * numeroDos;
                lblSuma.setText(String.valueOf(resultado));
                break;
            case "Division":
                if(numeroDos == 0){
                    lblSuma.setText("Error");
                }else{
                    resultado=numeroUno / numeroDos;
                    lblSuma.setText(String.valueOf(resultado));
                }
                break;
            default:
                throw new AssertionError();
        }
               
        
    }//GEN-LAST:event_btnSumaActionPerformed

    private void cbxSeleccionOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSeleccionOperacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSeleccionOperacionActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuma;
    private javax.swing.JComboBox<String> cbxSeleccionOperacion;
    private javax.swing.JLabel lbNumeroTres;
    private javax.swing.JLabel lblNumeroUno;
    private javax.swing.JLabel lblSuma;
    private javax.swing.JLabel lblTituloCinco;
    private javax.swing.JLabel lblTituloCuatro;
    private javax.swing.JLabel lblTituloOperacion;
    private javax.swing.JLabel lblTitulouno;
    private javax.swing.JTextField txtPrimerNumero;
    private javax.swing.JTextField txtSegundoNumero;
    // End of variables declaration//GEN-END:variables
}
